### ISSUE TITLE
Langchain PGVector is not working is not able to call the sql alchemy in vectorstore.py (missing package error)

### ISSUE THREAD

**Issue by sambasivaj24** [langchain-ai/langchain#21748]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import psycopg2
from langchain_postgres.vectorstores import PGVector
from langchain_community.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import GooglePalmEmbeddings
from langchain_google_genai import GoogleGenerativeAI
from langchain_core.documents import Document
from langchain_postgres import PGVector
# from langchain_postgres.vectorstores import PGVector
# from langchain_community.vectorstores import pgvector
import pgvector
# from pgvector.sqlalchemy import Vector

loader=TextLoader("/home/sambasiva/dev/fastapi-template/src/api/embedding_transformer/timeline.txt",encoding="utf8")
documents=loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=20)
chunks = text_splitter.split_documents(documents)
embeddings = GooglePalmEmbeddings(google_api_key=API)
connection = "postgresql+psycopg://vectorapi:vectorapipass@localhost:5432/vectordb"
collection_name = "my_docs"
db=PGVector.from_documents(embedding=embeddings,documents=chunks, collection_name=collection_name,connection=connection,)

print(len(chunks))
try:
  conn = psycopg2.connect(
      dbname="vectordb",
      user="vectorapi",
      password="vectorapipass",
      host="localhost",  # Optional, defaults to localhost
      port="5432"  # Optional, defaults to 5432
  )

  print("Connection successful!")
except Exception as e:
  print(f"Error connecting to database: {e}")

### Error Message and Stack Trace (if applicable)

sambasiva@USLDMJTG24:~/dev/fastapi-template$ /bin/python3 /home/sambasiva/dev/fastapi-template/src/api/embedding_transformer/test.py
Traceback (most recent call last):
  File "/home/sambasiva/dev/fastapi-template/src/api/embedding_transformer/test.py", line 25, in <module>
    db=PGVector.from_documents(embedding=embeddings,documents=chunks, collection_name=collection_name,connection=connection,)
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 1107, in from_documents
    return cls.from_texts(
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 975, in from_texts
    return cls.__from(
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 438, in __from
    store = cls(
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 308, in __init__
    self.__post_init__()
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 317, in __post_init__
    EmbeddingStore, CollectionStore = _get_embedding_collection_store(
  File "/home/sambasiva/.local/lib/python3.10/site-packages/langchain_postgres/vectorstores.py", line 91, in _get_embedding_collection_store
    from pgvector.sqlalchemy import Vector  # type: ignore
ModuleNotFoundError: No module named 'pgvector.sqlalchemy'; 'pgvector' is not a package

### Description

I am trying to use the langchain library to perform a RAG application but while using the pgvector as a database i encountered th issue with the langchain package langchain_postgres/vectorstores.py

in which it is giving the error of module not found and that pgvector is not a package

### System Info

langchain==0.1.19
langchain-community==0.0.38
langchain-core==0.1.52
langchain-google-genai==1.0.3
langchain-google-vertexai==1.0.3
langchain-postgres==0.0.4
langchain-text-splitters==0.0.1

platform windows
python version= 3.11

**Comment by maximeperrindev** [comment]
`pip install pgvector` should fix it

**Comment by sambasivaj24** [comment]
thank you, maximeperrindev, I tried the same, still getting the same error.

**Comment by saddamshahalachisoft** [comment]
I am having same issue... it was working fine and then suddenly this showing up. 

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[23], [line 1](vscode-notebook-cell:?execution_count=23&line=1)
----> [1](vscode-notebook-cell:?execution_count=23&line=1) db = PGVector.from_documents(
      [2](vscode-notebook-cell:?execution_count=23&line=2)     embedding=embeddings,
      [3](vscode-notebook-cell:?execution_count=23&line=3)     documents=top_texts,
      [4](vscode-notebook-cell:?execution_count=23&line=4)     collection_name=collection_name,
      [5](vscode-notebook-cell:?execution_count=23&line=5)     connection=connection,
      [6](vscode-notebook-cell:?execution_count=23&line=6)     use_jsonb=True,
      [7](vscode-notebook-cell:?execution_count=23&line=7) )

File d:\langchaindemo\lc2\env\Lib\site-packages\langchain_postgres\vectorstores.py:1731, in PGVector.from_documents(cls, documents, embedding, connection, collection_name, distance_strategy, ids, pre_delete_collection, use_jsonb, **kwargs)
   [1728](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1728) texts = [d.page_content for d in documents]
   [1729](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1729) metadatas = [d.metadata for d in documents]
-> [1731](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1731) return cls.from_texts(
   [1732](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1732)     texts=texts,
   [1733](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1733)     pre_delete_collection=pre_delete_collection,
   [1734](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1734)     embedding=embedding,
   [1735](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1735)     distance_strategy=distance_strategy,
   [1736](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1736)     metadatas=metadatas,
   [1737](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1737)     connection=connection,
   [1738](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1738)     ids=ids,
   [1739](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1739)     collection_name=collection_name,
   [1740](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1740)     use_jsonb=use_jsonb,
   [1741](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:1741)     **kwargs,
...
--> [106](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:106) from pgvector.sqlalchemy import Vector  # type: ignore
    [108](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:108) class CollectionStore(Base):
    [109](file:///D:/langchaindemo/lc2/env/Lib/site-packages/langchain_postgres/vectorstores.py:109)     """Collection store."""

ModuleNotFoundError: No module named 'pgvector.sqlalchemy'; 'pgvector' is not a package

**Comment by yaswanthkumargothi** [comment]
I figured out the solution for the same problem I have encountered.

This problem arises if you have different versions of python installed on your computer. please check the interpreter version and the environment version. 

If both didn't match, try "pip install pgvector" with the interpreter version.

Example:  C:/Python312/python.exe -m pip install pgvector
