### ISSUE TITLE
AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by ravi160822** [langchain-ai/langchain#3290]
getting this error when using postgreschatmessagehistory

**Comment by AmanSal1** [comment]
@ravi160822 can you please share a minimal code to reproduce the bug ?

**Comment by ravi160822** [comment]
just ran this, https://python.langchain.com/en/latest/modules/memory/examples/postgres_chat_message_history.html

**Comment by racinger** [comment]
same issue

**Comment by joelsimonoff** [comment]
@ravi160822 @racinger are you connected to a running database? If the `connection_string` is invalid then `psycopg.connect` will error and `self.cursor` will never be set. Please ensure you pass a valid `connection_string` for a running postgres db and try again.

**Comment by maejain-deloitte** [comment]
Tried:

```bash
sudo apt-get install libpq-dev
pip install psycopg
```

But it still shows this error:
```bash
File python3.8/site-packages/langchain/memory/chat_message_histories/postgres.py", line 83, in __del__
    if self.cursor:
AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'
```

**Comment by lordskyzw** [comment]
I simply changed to using MongoDB

**Comment by maejain-deloitte** [comment]
I fixed it as well:

Steps I took:
```bash
sudo apt-get install libpq-dev
pip install psycopg
pip install psycopg-binary
```

Connection string needs to be correct:
```python
history = PostgresChatMessageHistory(connection_string="postgresql://<connection_name>:<password>@localhost:<port>/<db_name>", session_id="foo")
```

For me this looked like:
```python
history = PostgresChatMessageHistory(connection_string="postgresql://postgres:postgres@localhost:5432/postgres", session_id="foo")
```

I don't but just recheck your file with this: https://python.langchain.com/en/latest/_modules/langchain/memory/chat_message_histories/postgres.html#PostgresChatMessageHistory

It works now!

**Comment by djpecot** [comment]
I'm also unable to connect to my db. I think it might have something to do with this line:

`self.connection = psycopg.connect(connection_string)`

This seems to hang and then I end up with no `connection`

For context, I've deployed my pg server with docker and am trying to run the [doc sample notebook](https://python.langchain.com/en/latest/modules/memory/examples/postgres_chat_message_history.html) locally. I'm not sure if this is possible as it seems that they need to be launched together from a docker file (new to Docker, so likely operator error as well here)

**Comment by fadilparves** [comment]
Hi
For those still getting the error as `connection is bad: Name or service not known` or `AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'` and you have tried @maejain-deloitte steps and still get error? Just make sure you don't have any special characters in your password. Somehow having @ or / or . in your password will cause the error. Hope helps if someone face the same issue in future. Btw thank you @maejain-deloitte

**Comment by Aman78695** [comment]
getting error:..AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'

**Comment by fadilparves** [comment]
@Aman78695 did you install pyscopg lib? Not the pyscopg2 library and make sure there is no special chars in your password because I realize that when passing password with special chars into the connection string it seems to cause the error saying port is password.
